src/commands/info.ts
This means that when run on a project directory without Nuxt we get Nuxt 3 defaults:
```
Working directory: /Users/daniel
Nuxt project info: (copied to clipboard)
------------------------------
- Operating System: Darwin
- Node Version:     v20.3.1
- Nuxt Version:     -
- CLI Version:      0.2.0
- Nitro Version:    -
- Package Manager:  unknown
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
👉 Report an issue: https://github.com/nuxt/nuxt/issues/new
👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new
👉 Read documentation: https://nuxt.com
```
=> fix: reverse conditions to default to v3

src/commands/dev-internal.ts
This PR allows leveraging non non-forked dev server using `nuxi _dev` for internal testing.
The random port can be controlled using `_PORT` environment variable.
=> feat: allow using internal `_dev` command for testing purpose

src/commands/dev.ts
resolves #103
This PR adds backward compatible `-o` and `-p` aliases for `--open` and `--port`.
Adding an alias for `-h` is impossible as is a reserved keyword for `--help` in citty.
I have also removed `--sslCert` and `--sslKey` from args to hide from usage as they are deprecated. (we might think about CLI warnings as well to eventually drop them and make sure usage is simple as much as possible)
=> fix(dev): add backward compatibility for `-o` and `-p` and deprecate `ssl*` args

src/commands/dev-internal.ts, src/commands/dev.ts
resolves #117
Since we now listen on the main process, this PR makes modules that depending on `listen` hook keep working.
**Note:** This is not a stable solution. Modules should not depend deeply on internal server listeners. 
Also, we pass the server without HTTPs to the vite-node server to avoid certificate issues as we had before.
--- 
Verified on tailwind module:
=> fix(dev): pass listener interface to the `listen` hook

src/commands/devtools.ts
Resolves #69 
This PR registers `command` as positional argument and reorders it before legacy `[rootDir]` option to align behavior with described in [docs](https://nuxt.com/docs/api/commands/devtools)
Also it changes defined command meta to give right output when user types `nuxi devtools` without specifying the action.
=> fix(devtools): define `enable|disable` command as positional argument

package.json, src/main.ts
We were missing nuxi version and description in usage
=> fix: add cli version and name in usage

src/commands/index.ts, src/commands/preview.ts
Resolves #113 by adding backward compatible `start` command.
Also improves the Preview mode experience with explicit warnings about production usage.
=> fix: improve preview banner and add backward compatible `start`

src/commands/dev-internal.ts, src/commands/dev.ts
resolves #112
Currently vite dev server listens on a dedicated port to handle HMR events with WebSocket support. 
When the main dev server is listening on HTTPs, Vite HMR server also needs a secure protocol `wss://`. 
We wouldn't need it in the close future when can reuse same port but until then it is required in order to have vite HMR with HTTPs
=> fix(dev): pass `https` info to the vite hmr

.eslintrc, package.json, playground/app.vue, playground/modules/ws.ts, playground/nuxt.config.ts, playground/pages/index.vue, playground/pages/ws.vue, playground/server/ws.ts, pnpm-lock.yaml, src/commands/dev.ts
#108
#101
This PR adds support for `upgrade` event from dev server wrapper, proxying it to the underlying (build time) userland server instance.
I have also added a simple playground page to try things out (it is obviously not a right usage to register ws but current workaround)
=> fix(dev): support ws upgrades

src/commands/build-module.ts
This PR depends on https://github.com/nuxt/module-builder/pull/163 which has now been merged and [released](https://github.com/nuxt/module-builder/releases/tag/v0.5.1).
Adding the sourcemap option is useful for those debugging built modules using a debugger.
=> feat(build-module): add `--sourcemap` support

src/commands/dev.ts
Resolves #144
When `devServer.https` options are provided, we should enable https mode by default (can be temporarily disabled with `--no-https`)
=> fix(dev): enable `https` by default when `devServer.https` options is set

src/commands/dev.ts
resolves #135
hard restart support were missing in initial new dev server impl.
This PR also fixes small relevant issues:
- avoid mutating `process.argv` (for subsequent reloads)
- register (main) graceful shutdown hooks once
- avoid exiting main process when child restarts with code 0 (internally by parent)
Playground: (WSS is buggy, need to rename `playground/modules` dir)
```ts
export default defineNuxtConfig({
hooks: {
ready(nuxt) {
setTimeout(() => {
console.log('sending hard restart...')
nuxt.callHook('restart', { hard: true })
}, 1000)
},
},
})
```
=> fix(dev): handle hard restart

src/commands/info.ts, src/main.ts, src/utils/banner.ts, src/utils/engines.ts, src/utils/update.ts
Use import assertion + default import of package.json. While this adds (relatively) little to the dist size, helps better compatibility with using Bun and other toolings.
=> refactor: import `package.json` with json assertion

src/commands/dev.ts
related #150
When forking is not appropriate (testing for performance and coverage) and bun for compatibility, we can auto-flip the `--fork`/`--no-fork` default.
=> fix(dev): disable forked mode by default for bun and test

src/commands/build.ts, src/utils/kit.ts
This PR resolves #157
Previously we were having a polyfill for `writeTypes` that is only available in Nuxt 3.7+. 
This PR adds it from one place so in the future, we don't forget in some places.
=> fix(dev): add polyfill for `writeTypes`

src/commands/dev.ts
While normally no modules should directly call `process.exit(0)` within nuxt build process / dev, some might (for example for testing). 
This PR uses internal `SIGHUP` which is commonly used in UNIX processes as restart indicator for internal reload (we shall later also support it for main process)
=> fix(dev): use dedicated signal for restart

src/commands/dev.ts
Fixes regression from #166
The default host should be `undefined` in order to allow listhen setting proper default. Schema always adds `''` (anyhost) as default which we accidentally started using it again (which needs to be fixed in nuxt btw /cc @danielroe)
=> fix(dev): default host should be `undefined`

src/utils/dev.ts
This PR enables Nuxt to use main dev server as HMR server instead of requiring an external port.
Instead of updating Nuxt, using hook in nuxi allows moving forward faster and keep it closer to the listener.
~~Current issues: Vite keeps hooking on internal web server for ws. After a (soft) reload, hmr will be broken~~
Currently, seems quite fast and stable. 
https://github.com/nuxt/cli/assets/5158436/b23573f9-61d1-4611-bac6-73cc511f69dd
=> feat(dev): reuse main dev port for vite hmr

src/utils/dev.ts
Followup on #184
Since this is a new feature, there might be conditions we might want to disable hmr port integration. ~~Also seems bun has some issues which we might need to disable for bun for now.~~ 
This PR allows disabling the effect of #184 using `NUXI_DISABLE_VITE_HMR` env. It is not a flag since probably won't last long.
=> chore: allow disabling vite hmr port integration

src/commands/init.ts
This PR introduces the `manager` CLI argument, allowing users to skip the package manager selection prompt.
resolves https://github.com/nuxt/cli/issues/161
=> feat(init): support `--package-manager` 

src/commands/module/_utils.ts, src/commands/module/add.ts
- resolves #194
- resolves https://github.com/nuxt/rfcs/issues/31 (from 2019!)
----
Search in [nuxt/modules](https://github.com/nuxt/modules) database when adding a new module. This allows installing modules as easy as `nuxt module add tailwindcss`.
This feature checks for possible compatibility issues and confirms whether to continue or not.
`nuxi module add axios` on a nuxt 3 project:
In case of network issues, we fall back with a warning and use the input as npm package name without validation. This could be improved later with `--preferOffline` and a disk cache of modules (to be used also for search functionality). (PR welcome!)
Some Nuxt modules use different major versions for different Nuxt versions (such as image Module).
With the introduction of `compatibility.versionMap` in …
=> feat: modules db integration with `nuxi module add`

src/commands/dev-child.ts, src/commands/dev.ts, src/utils/dev.ts
resolves #205
This PR includes a refactor to preserve more context of dev server / proxy and give it to the internal `listener` instance that is passed to `listen` hook usable for modules.
```ts
export default defineNuxtConfig({
hooks: {
listen: async (_server, listener) => {
console.log('listener.url', listener.url)
console.log('listener.getURLs', JSON.stringify(await listener.getURLs()))
},
},
})
```
```
listener.url http://localhost:3000/                                                                                                              
listener.getURLs [{"url":"http://localhost:3000/","type":"local"},{"url":"http://127.0.0.1:50409/","type":"local"}]   
```
=> fix: make dev proxy url available for `listen` hook

src/commands/dev.ts, src/utils/dev.ts
When running in `--no-fork` mode (enabled by default for bun and test), we do not need a proxy server and can directly listen in main thread.
An edge case of disadvantages with this method is that when using `--https` with self-signed cert, Node.js fetch requests passing `NODE_TLS_REJECT_UNAUTHORIZED=0` in order for vite dev server working. For now i added a warning to guide users in such edge cases.
Also resolves #190 (issues with bun hanging)
=> perf(dev): avoid using proxy with `--no-fork` mode

src/commands/module/add.ts
=> fix: prompt to abort `module add` if install failed

src/utils/dev.ts
Related to #181 
This PR fixes issues with `nuxt dev --no-fork` when running inside a Docker container.
Docker networking by default is IPv4 only while Node.js listener address reports an IPv6 anyhost. 
This PR, handles this special case by preferring `localhost` over `[::]` (reported by Node). Since anyhost is also reachable via localhost, this also works outside of Docker environments.
=> fix(dev): prefer `localhost` over `[::]` for internal networking

.github/workflows/ci.yml, src/commands/info.ts, src/commands/test.ts, src/utils/banner.ts, src/utils/kit.ts
part of https://github.com/nuxt/nuxt/issues/22143
needs to be merged before: https://github.com/nuxt/nuxt/pull/23508
related: https://github.com/nuxt/cli/commit/d1120b1
=> fix: support `-nightly` nuxt releases and publish `nuxi-nightly`

src/commands/analyze.ts
This should be backwards compatible as we just checking truthiness of this option in previous versions of Nuxt.
Once https://github.com/nuxt/nuxt/pull/23856 is merged, we will then be able to respect user-set defaults in `nuxt.config`.
resolves https://github.com/nuxt/cli/issues/238
=> fix(analyze): don't override analyze options

src/commands/module/add.ts
This pr replaces the for loop to check if the modules array contains the added module, with a more performant `Array.includes`.
```
"Array.includes time:" 30 "ms"
"Manual loop time:" 326 "ms"
"Array.includes time:" 27 "ms"
"Manual loop time:" 242 "ms"
```
If the purpose of the for loop is backward compatibility, ignore this pr. 
🔥💚
=> refactor: use magicast `.includes` helper

src/commands/init.ts
Fixes #213
---
I've tested this out locally using:
```shell
node {path_to_locally_built_cli_with_this_change}/bin/nuxi.mjs init . --force
```
=> fix(init): use absolute path for installing dependencies

run.ts, src/commands/dev.ts
Resolves #274
Normally process.argv is same as ctx.rawArgs but when using programmatic API, the args can be different (like containing a custom root dir)
=> fix(dev): pass programmatic args to sub process

src/commands/analyze.ts, src/commands/cleanup.ts, src/commands/upgrade.ts, src/utils/nuxt.ts
Resolves #225
Respect custom `buildDir` option if provided to clean instead of default `.nuxt` dir
=> fix(analyze, cleanup, upgrade): respect custom `buildDir`

src/commands/init.ts
This removes the npmrc with shamefully-hoist=true for pnpm Package Manager as it's not needed anymore
Closes https://github.com/nuxt/starter/issues/547
Closes https://github.com/nuxt/cli/issues/316
=> fix: don't write `.npmrc` with `shamefully-hoist=true` anymore

src/commands/init.ts
This PR fix the issue happening when one run `nuxi init .` in a directory whose path contains spaces.
It just surround the path variable with in double quote in the string literal.
(This is my first public PR, I've looked for a contribution guide but did not find it... If there is anything wrong with the way I made it feel free to discard it and fix the concerned line directly, I'll learn by watching :wink: )
=> fix: handle spaces in path at repo initialization

src/commands/analyze.ts, src/commands/build.ts, src/commands/prepare.ts, src/commands/typecheck.ts, src/utils/dev.ts
close https://github.com/nuxt/cli/issues/349
=> refactor: migrate to `cwd` from `rootDir`

src/utils/dev.ts
This was causing errors for apps with custom `baseUrl` and making dev server non-usable at all
=> fix(dev): prepend `baseURL` for vite hmr ws upgrade

src/utils/templates.ts
This PR is to change the `<script setup lang="ts">` block in the templates for `component`, `layout`, and `page` to match official Vue [documentation](https://vuejs.org/guide/typescript/composition-api.html). 
Previous templates:
`<script lang="ts" setup>`
Official Vue documentation:
`<script setup lang="ts">`
=> change script setup in templates to match Vue documentation

src/commands/upgrade.ts
Hi :wave: 
This PR adds `-w` arg to the install command when having pnpm and pnpm workspaces. Pnpm prevents running installing new deps in the root directory without `-w`
=> fix: use -w arg for pnpm root workspace

src/commands/dev.ts, src/utils/dev.ts
related: https://github.com/nuxt/nuxt/issues/28474
When passing a relative `app.baseURL`, this should not affect how the server is started. This applies the same fix in Nuxt `runtimeConfig`:
https://github.com/nuxt/nuxt/blob/d1c40328fe959f05ae77cc66311c40d5f151a109/packages/schema/src/config/nitro.ts#L18-L20
=> fix(dev): handle relative baseURL

.github/workflows/autofix.yml, .github/workflows/ci.yml
This PR aims to run tests on Windows in CI, to avoid potential regressions.
related: https://github.com/nuxt/ecosystem-ci/pull/15
=> ci: run test suite on windows

src/commands/dev.ts
Resolves #403 
respect the `--inspect` argument that is passed to `nuxi dev`
It's not easy to attach the debugger to a nuxt running in docker beacuse --inspect is passed without host (typically 0.0.0.0) and port.
it now passes the argument as it's passed by the user
Typical values could be
- nuxi dev --inspect
- nuxi dev --inspect=0.0.0.0
- nuxi dev --inspect=9229
- nuxi dev --inspect=0.0.0.0:9229
at the moment only the first option works but all the other are supported (just filtered out)
=> fix(dev): respect explicit address and port in `--inspect`

src/commands/_shared.ts, src/commands/build.ts, src/commands/dev-child.ts, src/commands/dev.ts, src/commands/generate.ts, src/commands/prepare.ts, src/commands/preview.ts, src/utils/dev.ts
This PR is proposing to add a new `--env [name]` attribute to Nuxi. The attribute will be passed to the `envName` option of the c12 library. This adds the ability to support environment overrides (environment-specific configuration) for custom environments. Currently, c12 supports that and the types of the nuxt configuration file are aware of that, but there is no way to actually use custom environments, because `NODE_ENV` cannot be set to values other than `production` or `development`. This PR closes the gap, making deployments to different environments easier.
See #357.
Should this be approved, I would be happy to amend the documentation accordingly.
=> feat: add env-flag for env-specific config (#357)

pnpm-lock.yaml, src/commands/info.ts
Resolves https://github.com/nuxt/nuxt/issues/29603
This pull request is intended to fix an issue whereby running the `npx nuxi@latest info` command doesn't list the necessary information to the console. This pull request intends on fixing that by adding an `await` keyword infront of the `getNuxtConfig` function.
=> fix(info): await loading of nuxt config file

src/commands/build.ts
Resolves #513
resolves nuxt/nuxt#29525
This PR ensures that the `NITRO_PRESET` and `SERVER_PRESET` environment variables are passed to nuxt kit for nitro overrides. It also follows the same order of priority as nitro (i.e. cli argument -> `NITRO_PRESET` -> `SERVER_PRESET`)
=> fix(build): respect environment variable preset overrides

src/commands/module/add.ts
Resolves #510 
Fixes resolving of wrong registry from .npmrc file
Checks if the modules is under a scope, and checks the .npmrc file for a matching registry with fallback to overwritten default registry.
=> fix: find correct registry for package installation (#510)

src/commands/typecheck.ts
Fix #461.
If user is running on Bun, use `bunx` to install deps globally and run `vue-tsc` to type check.
=> fix(typecheck): use bunx if is running on bun

src/commands/init.ts
Resolves #525. It is pending another PR to add Deno support for `nypm` (https://github.com/unjs/nypm/pull/158).
=> Add support for Deno

src/commands/analyze.ts
* #390 
* Resolves #390 
This changes the `analyze` command to change the chunk filenames to include the original human readable filename. 
~~@manniL 
In the issue you mention removing the hash entirely, if that's preferable I can change the PR. I figured including the hash could prevent duplicate filenames (not sure if possible) and in case these are used to invalidate build cache (I have no idea 🤷)~~
=> fix: `analyze` should include original readable filenames

src/commands/add.ts, src/utils/templates.ts, test/unit/templates.spec.ts
* #551 
Resolves #551 
Changes the generated api template path to be resolved from `rootDir` instead of `srcDir` if `compatibilityVersion: 4`, not sure if other templates should be from `rootDir` as well, let me know.
I also changed the template paths to use the config `dir` where applicable, not sure if there's an open issue for this 🤔
=> fix(add): respect custom dirs from nuxt project

src/commands/cleanup.ts, src/utils/nuxt.ts
* #533 
Resolves #533 
It seems like, after running the dev server when using `compatibilityVersion: 4`, loading the nuxt config will no longer give the configured `buildDir` which will instead be set to something like `/node_modules/.cache/nuxt/.nuxt`. This is not very useful as we're already clearing the `/node_modules/.cache` directory with this command.
I'm not entirely sure what causes this change, but I did find that passing `overrides: { dev: true }` to `loadNuxtConfig` returns the expected values, not sure if this has other unintended consequences, we're only using the `rootDir` and `buildDir` from the loaded config.
=> fix(cleanup): remove dev buildDir, not production

src/commands/_shared.ts, src/commands/analyze.ts, src/commands/build.ts, src/commands/dev.ts, src/commands/generate.ts, src/commands/prepare.ts, src/commands/preview.ts
* #542 
Resolves #542 
Not sure if bug fix or feature, but it makes sense users want to run analyze using the same options as the build command (should analyze actually be an option/flag for the build command?). 
I haven't actually tested whether the env file is being used, not sure what an easy way is to check this, but I simply applied the flag the same way as in the build command.
This PR also moves the `--dot-env` args into `src/commands/_shared.ts` like other common/shared flags.
=> fix: support `--dotenv` for `analyze`

src/commands/_shared.ts, src/commands/add.ts, src/commands/analyze.ts, src/commands/build-module.ts, src/commands/build.ts, src/commands/cleanup.ts, src/commands/dev-child.ts, src/commands/dev.ts, src/commands/devtools.ts, src/commands/generate.ts, src/commands/info.ts, src/commands/init.ts, src/commands/module/add.ts, src/commands/module/search.ts, src/commands/prepare.ts, src/commands/preview.ts, src/commands/test.ts, src/commands/typecheck.ts, src/commands/upgrade.ts
* #450
Is this a refactor and/or docs change 🤷
I found the `ROOTDIR` and `cwd` default value or fallback value a bit confusing, these changes _should_ be functionally the same but instead handles the fallback to the shared argument configuration. Please make sure to check I'm not misunderstanding the fallback logic 😬
I'm slowly working on syncing the descriptions between the command usage `-h` output and those described on `docs/api/commands` pages, more PRs to come.
=> refactor: shared command descriptions and `--cwd` default

src/commands/dev.ts
resolves https://github.com/nuxt/cli/issues/595
`SIGHUP` is not supported on windows
=> fix(dev): use `SIGTERM` instead of `SIGHUP` on windows

src/commands/module/add.ts
* #65
Resolves #65
Closes #233 
This is an updated version of https://github.com/nuxt/cli/pull/233 (credited in commit).
The original implementation triggered a dependency installation for each module, I have made changes so that only one single installation is triggered.
=> feat(module): add multiple modules at once

src/commands/module/add.ts
resolves https://github.com/nuxt/nuxt/issues/30304
=> fix(module): pass resolved `cwd` to `addDependency`

README.md, src/utils/templates.ts
This PR adds the `layer` template to the `add` command. This creates a directory of `<name>` with a base `nuxt.config.ts` file.
```bash [Terminal]
npx nuxi add layer subscribe
```
A PR with the documentation update is ready to be open here : https://github.com/clemcode/nuxt/tree/docs/nuxi/add-layer
=> feat(add): add layer template

src/commands/info.ts, src/commands/upgrade.ts, src/utils/fs.ts, src/utils/packageManagers.ts
resolves #617
This PR replaces old code with nymp's apis of `detectPackageManager` and `addDependency`.
As a bonus, we're now also supporting deno for free since nypm does
=> fix(upgrade): use nypm in upgrade and info commands

src/commands/build.ts
resolves #555
Related to #555, possibly resolves it?
We currently override any configured preset with `static`, instead we should let nitro resolve the appropriate preset by passing `static: true` since it supports several static presets.
=> fix: do not override `preset` when prerendering

.github/workflows/size.yml, .gitignore, build.config.ts, package.json, pnpm-lock.yaml
=> ci: add bundle size comparison job

src/commands/prepare.ts, src/commands/typecheck.ts, src/utils/kit.ts
This finally drops the inlined `writeTypes` utility from Nuxt <3.7, which was last published 19 July 2023.
=> perf: do not inline `writeTypes` from `@nuxt/kit`

eslint.config.js, src/commands/add.ts, src/commands/analyze.ts, src/commands/build-module.ts, src/commands/build.ts, src/commands/dev-child.ts, src/commands/dev.ts, src/commands/devtools.ts, src/commands/info.ts, src/commands/init.ts, src/commands/module/add.ts, src/commands/module/search.ts, src/commands/prepare.ts, src/commands/preview.ts, src/commands/test.ts, src/commands/upgrade.ts, src/main.ts, src/utils/banner.ts, src/utils/dev.ts, src/utils/engines.ts, src/utils/env.ts, src/utils/fs.ts, src/utils/logger.ts, src/utils/nuxt.ts
=> feat: add `nuxi` tag to logs

src/commands/build-module.ts, src/commands/info.ts, src/commands/module/_utils.ts, src/commands/module/add.ts, src/utils/banner.ts
=> fix: handle failures to resolve deps

.github/workflows/ci.yml, package.json
=> ci: split out lint + release workflows

src/commands/module/add.ts
resolves https://github.com/nuxt/cli/issues/229
This better communicates which modules are already installed and skips their installation.
=> feat(add): skip installation of already installed modules

test/e2e/commands.spec.ts
=> test: try running exec in tests with tinyexec

knip.json, src/commands/init.ts, test/e2e/commands.spec.ts
=> test: add `init` and `add` e2e tests

scripts/release.mjs, src/commands/devtools.ts, src/commands/preview.ts, src/commands/typecheck.ts, test/e2e/commands.spec.ts
this ensures we throw when errors are occurred when spawning child processes
=> fix: throw when errors are encountered

packages/nuxi/src/utils/dev.ts, packages/nuxi/src/utils/fs.ts, packages/nuxi/src/utils/nuxt.ts
two small perf changes - this avoids writing a file which will immediately be removed, and also doesn't block the directory clearing until the file has been written
it also persists `nuxt.json` even when clearing the build directory
=> perf(dev): avoid removing manifest immediately after creation

packages/nuxi/src/commands/init.ts, packages/nuxi/src/commands/module/add.ts, packages/nuxi/src/commands/upgrade.ts
`consola.prompt` returns a Symbol when `Ctrl-C` is called - we can't trust the types on this one.
=> fix(init,module,upgrade): validate response from `consola.prompt`

packages/nuxi/src/commands/dev-child.ts, packages/nuxi/src/commands/dev.ts, packages/nuxi/src/utils/dev.ts
resolves https://github.com/nuxt/nuxt/issues/30725
this automatically sets the new `allowedHosts` vite option when used with an explicit `--host`
=> fix(dev): automatically set `allowedHosts` + `origin` w/ `--host`

packages/nuxi/src/commands/module/add.ts, packages/nuxi/test/unit/commands/module/add.spec.ts
fix #697 #701
resolves #697, resolves #701 
This PR enhance the `nuxi module add` but allowing it to find a Nuxt Module when a version is speficied.
Without this PR:
With this PR:
=> fix(module): allow specifying version alongside module name

packages/nuxi/src/commands/dev-child.ts, packages/nuxi/src/commands/dev.ts, packages/nuxi/src/utils/dev.ts
resolves https://github.com/nuxt/nuxt/issues/31184
this gets URLs from tunnels and automatically adds them to vite's allow-list for hosts
=> fix(dev): automatically add tunnel hostnames to vite allowedHosts

packages/nuxi/src/commands/init.ts, packages/nuxi/src/commands/module/add.ts
resolves https://github.com/nuxt/cli/issues/754
POC for the interactive modules selector - feedback and suggestions are welcome!
=> feat(init): add interactive modules selector

packages/nuxi/src/commands/init.ts, packages/nuxi/src/commands/module/add.ts
A few small improvements and fixes I didn't manage to address on time in https://github.com/nuxt/cli/pull/781:
- removing full stop from description only from the end (purely for future proofing)
- applying two conditions in a single `.filter()`
- forwarding log level arg via `module add` to `prepare` command it uses
- skipping running `prepare` command if `skipInstall` is passed (otherwise we're getting errors!)
=> fix(init): improve interactive modules selector

packages/nuxi/src/utils/dev.ts
Errors thrown while loading were hard to debug as they only were present in the title of the page
Now they look like this:
(reproduction from https://github.com/nuxt/nuxt/issues/31222)
=> fix(dev): use `nitro` to render errors thrown while loading

packages/nuxi/src/commands/dev-child.ts, packages/nuxi/src/commands/dev.ts, packages/nuxi/src/utils/dev.ts
closes https://github.com/nuxt/nuxt/pull/31360
resolves https://github.com/nuxt/nuxt/issues/31318
this respects user's configuration in `devServer.cors` + `vite.server.allowedHosts` whilst always overriding these values if `--public` or codesandbox environment is found.
=> fix(dev): allow overriding inferred cors/allowedHosts config

packages/nuxi/src/commands/module/add.ts, packages/nuxi/test/unit/commands/module/add.spec.ts
Fix for https://github.com/nuxt/cli/issues/697
The code verify if the `pkgVersion` is only a single number to then perform a search for the highest major version.
Previously PR fix part of the problem but not allow to install full package from a single major version.
This PR enhance the `nuxi module add` to allowing it to find a Nuxt Module full version when only a major is specified.
Without this PR:
With this PR:
Regression:
> default installation not affected
-----------------------------------------------------------------------
=> fix(module): resolve semver module versions

packages/nuxi/src/commands/init.ts
This PR detects the pm used when running the nuxi init (create nuxt) and sets it as the default for the pm selection.
Tested all (!deno) pms locally.
=> feat(init): default to install with current package manager

packages/nuxi/src/commands/dev.ts
resolves https://github.com/nuxt/cli/issues/854
we were only respecting 'top' layer host config for some reason - this allows any layer to set the default host (as well as port)
=> fix(dev): respect `devServer.host` if set in layer

packages/nuxi/bin/nuxi.mjs, packages/nuxt-cli/bin/nuxi.mjs
this enables the node compile cache following [the pattern in jiti](https://github.com/unjs/jiti/blob/b396aec45847a32677417ea9dfc78098b6d45c23/lib/jiti-cli.mjs#L17)
thanks @pi0 for the tip ❤️
=> perf: enable node compile cache

packages/nuxi/src/commands/typecheck.ts
resolves https://github.com/nuxt/cli/issues/323
resolves https://github.com/nuxt/cli/issues/926
with the upcoming v4 nuxt release, and https://github.com/nuxt/nuxt/issues/32343, it's now possible to typecheck all three contexts (node/app/nitro) of a nuxt project with a single command.
Make sure you are running v4 alpha 3 or newer, and follow the steps here: https://nuxt.com/docs/4.x/getting-started/upgrade#typescript-configuration-changes
=> feat(typecheck): support ts projects

packages/nuxi/src/utils/kit.ts
currently we might pick an older version of nuxt/kit if a module has installed it and it's available locally.
this ensures we prefer the version of kit matching _nuxt_. (newer versions of kit, if installed, might be deduplicated by package manager but should 'flow down', so this is safer - and should also be more performant)
=> fix: prioritise `@nuxt/kit` from `nuxt` dependencies

package.json, packages/nuxi/src/dev/index.ts, playground/test/e2e/build.spec.ts, playground/test/e2e/dev.spec.ts, vitest.config.ts
A regression from https://github.com/nuxt/cli/pull/921, this ensures if `_PORT` is set that we don't create a socket but instead listen on that port.
=> fix(dev): ensure we listen on port if `_PORT` is set

packages/nuxi/src/dev/utils.ts
a regression - nuxt was only restarting the first time the config file was changed
=> fix(dev): only close config watchers when process exits

packages/nuxi/src/commands/dev.ts
resolves https://github.com/nuxt/cli/issues/964
this uses `SIGTERM` on deno rather than passing `0`, which is not supported.
=> fix(dev): use 'SIGTERM' to kill process on deno

packages/nuxi/src/commands/upgrade.ts
This should fix #979 by setting Nuxt 4 as the default version. However, I'm not sure about the nightly version update or if anything else needs to be updated elsewhere.
=> fix(upgrade): update default Nuxt version to v4

.github/workflows/size.yml
Only with `pull_request_target` does the action actually have the ability to make PR comments.
Please note: `pull_request_target` is dangerous in general. In this case, each job has restricted permissions defined, so it can be safely used here without a risk of anyone pushing unauthorized code. (`pull-requests: write` does not allow merging a PR).
You can't see the issue in this PR, because the new permissions will only apply after this PR is merged, but GitHub doesn't run the old action because it changed. You can see it in the checks tab of my other PR #998.
=> fix(ci): Give correct permissions to PR size compare workflow

packages/nuxi/src/commands/init.ts
I could not find one, let me know if I should open one.
Previously, when the user selected a directory that already existed, and was then prompted to choose a different directory, and then selected a different directory, and also chose official modules to add, the official modules would be added to the initial directory, not the newly chosen one.
=> fix(init): use amended directory when adding modules

packages/nuxi/src/commands/upgrade.ts
resolves https://github.com/nuxt/cli/issues/484
This PR introduces the following new channels: `v3`, `v4`, `v3-nightly` and `v4-nightly`.
This should allow `nuxt upgrade` to be used to upgrade minor versions of v3
```sh
pnpx nuxt@latest upgrade --dedupe --channel=v3
```
=> feat(upgrade): add `v3`, `v4`, `v3-nightly` and `v4-nightly` channel

packages/nuxi/src/commands/init.ts
- The detection of the installed modules was not working, using `await import()` was wrong, fixed it by using `readPackageJSON`
- I also detected ahead of time if nuxt is installed as dependency to avoid asking to install Nuxt modules
- This gives the possibility to install the Nuxt UI templates with Vite while keeping our nice Nuxt branding and CLI
=> fix(init): properly check installed modules
